### PR TITLE
Added mouse wheel interactivity

### PR DESCRIPTION
**Pull request by vipulbhj**
This works on #3 

I tried to solve the formatting issues, as much I could, but some of them I couldn't. Let me know, if this is doable, else I will clone it again and do it.

### CODE REVIEW

**Comment by vipulbhj** [comment]
@francisrstokes Hey 👋, is this okay ?

**Comment by francisrstokes** [comment]
Hi @vipulbhj, sorry for the late reply. I think it's a great start, but will need some more work in order to merge. The biggest point is that bringing in the whole `blessed` library is a bit much as it's an entire framework for creating interactive CLI (much like ink), and we're only utilising the scrolling/mouse functionality. The good thing is that with this PR, the concept itself is proven to work. The way forward, as I see it, would be to dig into the `blessed` code to see how they're handling the mouse, and bring that approach into the `bewitched` code (not a direct copy paste of course, but the ideas and mechanics).
The second minor point would be the styling - probably best to turn off your auto linting and to follow the style of the existing code (or configure your linter to fix according to the style). There are a few files that have quite a number of changes that are unrelated to the PR, and although merging them would not be the end of the world, it does make it harder to search through the commit history and understand how parts of the code evolved. I would suggest performing an interactive rebase in git, fixing the styling, and re-applying your actual changes).

I hope it makes sense, and that you don't think I'm being too critical - because it's not the intention. If you don't have the time to continue working on it, I won't hold it against you! But from my perspective it's coming along well, just needs a bit of tuning up and refinement :+1:

**Comment by vipulbhj** [comment]
Hey @francisrstokes, all those points make sense, and I would definitely be interesting in diving in the library and bringing over the parts which are responsible for scroll, but I am not sure if I can do this quickly. If time is not an issue with you, I can continue working on this.

**Comment by francisrstokes** [comment]
@vipulbhj absolutely no rush, no pressure! If you're working on it, it should be because you find it interesting or enjoyable. Go at your own pace, and if you have specific questions then feel free to ask - I'll help if I can :+1:

**Pull request closed without merging**
